### ISSUE TITLE
在 config.yaml 中指定的 geoip.dat/geodata.dat 路径不生效

### ISSUE THREAD

**Issue by trantuan-20048607** [apernet/OpenGFW#127]
在`config.yaml`中指定**已存在的** geoip.dat/geodata.dat 作为 OpenGFW 的数据源：
```yaml
...
geo:
  geoip: /path/to/geoip.dat
  geosite: /path/to/geosite.dat
```
运行后 OpenGFW 无视了这两条配置，始终在`$(pwd)`中寻找数据库，若找不到则自动下载。换成**存在上级目录但不存在文件**的路径后同样无效，但直接`ln -s /path/to/geoip.dat geoip.dat`有效，这也是目前采用的解决办法。

**Comment by haruue** [comment]
检查了下代码貌似是文档写错了。。
试试看下面这样呢？
```yaml
ruleset:
  geoip: /path/to/geoip.dat
  geosite: /path/to/geosite.dat
```
