### ISSUE TITLE
请为美国人民添加阻断Tik Tok的功能

### ISSUE THREAD

**Issue by MakiseKurisu** [apernet/OpenGFW#155]

**Comment by haruue** [comment]
本来就支持吧

```yaml
- name: block tiktok by http host & geosite
  action: block
  expr: geosite(string(http?.req?.headers?.host), "tiktok")

- name: block tiktok by tls sni & geosite
  action: block
  expr: geosite(string(tls?.req?.sni), "tiktok")
```
